### ISSUE TITLE
Fix Crash

### ISSUE THREAD

**Issue by joshy** [pacs-ris-crawler/pacs-ris-crawler#5]
To reproduce
1. Search something with empty result
2. Click export patient data
3. Search -> Internal server error

**Comment by joshy** [comment]
```code
[2022-01-21 15:07:06 +0100] [27903] [ERROR] Error handling request /export_anon
Traceback (most recent call last):
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
     response = self.handle_exception(e)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pacs-ris-crawler/web/meta/views.py", line 146, in export_anon
    df = df.drop(["PatientName", "PatientBirthDate"], axis=1)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/var/www/env3.6_meta/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['PatientName' 'PatientBirthDate'] not contained in axis
```
